// <auto-generated />
using System;
using CMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMS.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210206063647_refactoredDataSet")]
    partial class refactoredDataSet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CMS.Data.Core.Course", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CMS.Data.Core.CourseManagement", b =>
                {
                    b.Property<int>("CourseManagementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("CourseManagementId");

                    b.HasIndex("CourseID");

                    b.ToTable("CourseManagements");
                });

            modelBuilder.Entity("CMS.Data.Core.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("BirthdayDay")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CourseManagementId")
                        .HasColumnType("int");

                    b.Property<string>("FirstMidName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Grades")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CourseManagementId");

                    b.HasIndex("TeacherID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CMS.Data.Core.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("CMS.Data.Core.Teacher", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("BirthdayDay")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CourseManagementId")
                        .HasColumnType("int");

                    b.Property<string>("FirstMidName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("CourseManagementId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("CMS.Data.Core.CourseManagement", b =>
                {
                    b.HasOne("CMS.Data.Core.Course", null)
                        .WithMany("CourseManagement")
                        .HasForeignKey("CourseID");
                });

            modelBuilder.Entity("CMS.Data.Core.Student", b =>
                {
                    b.HasOne("CMS.Data.Core.CourseManagement", null)
                        .WithMany("Students")
                        .HasForeignKey("CourseManagementId");

                    b.HasOne("CMS.Data.Core.Teacher", "Teacher")
                        .WithMany("Student")
                        .HasForeignKey("TeacherID");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("CMS.Data.Core.Subject", b =>
                {
                    b.HasOne("CMS.Data.Core.Course", "Course")
                        .WithMany("Subject")
                        .HasForeignKey("CourseID");

                    b.HasOne("CMS.Data.Core.Teacher", "Teacher")
                        .WithMany("Subject")
                        .HasForeignKey("TeacherID");

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("CMS.Data.Core.Teacher", b =>
                {
                    b.HasOne("CMS.Data.Core.CourseManagement", null)
                        .WithMany("Teachers")
                        .HasForeignKey("CourseManagementId");
                });

            modelBuilder.Entity("CMS.Data.Core.Course", b =>
                {
                    b.Navigation("CourseManagement");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("CMS.Data.Core.CourseManagement", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("CMS.Data.Core.Teacher", b =>
                {
                    b.Navigation("Student");

                    b.Navigation("Subject");
                });
#pragma warning restore 612, 618
        }
    }
}
